stages:
  - build
  - deploy

variables:
  FIREBASE_PROJECT_ID: "componentchecklist"
  CI_NODE_IMAGE: "node:16"

cache:
  key: "node_modules"
  paths:
    - node_modules/

before_script:
  - echo "Setting up..."
  - npm ci --cache .npm --prefer-offline

install_dependencies:
  image: $CI_NODE_IMAGE
  stage: build
  script:
    - npm install

build_project:
  image: $CI_NODE_IMAGE
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build/

deploy_to_firebase:
  image: $CI_NODE_IMAGE
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase use --token $FIREBASE_TOKEN $FIREBASE_PROJECT_ID --debug
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - frontend-fix
    - main


